DROP DATABASE IF EXISTS avant;
CREATE DATABASE avant;
USE avant;

CREATE TABLE card(
    id INTEGER(11) AUTO_INCREMENT NOT NULL,
    card_number BIGINT NOT NULL,
    credit_limit INTEGER(10) NOT NUll,
    APR INTEGER(3) NOT NUll,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    balance DECIMAL(5, 2) NOT NUll,
    PRIMARY KEY(id)
);

CREATE TABLE transactions(
    transID INTEGER(11) AUTO_INCREMENT NOT NULL,
    amount DECIMAL(5, 2) NOT NUll,
    ownerID INTEGER(11),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(transID),
    FOREIGN KEY (ownerID) REFERENCES card(id)
);
